#ifndef _COMMON_H_
#define _COMMON_H_

#define PORT_ID				7856
#define IP_ADDRESS_NAD		"192.168.0.1"

#define BUF_SIZE			1024

#define NO_ERROR			0
#define ERR_CHKSUM			1
#define ERR_GROUP_ID		2	
#define ERR_MESSAGE_ID		3

enum err_id {ID_CMT=1, ID_CARMCU, ID_V2X, ID_NAD};

enum msg_id {
	ECHO_ETH_REQ=1,
	ECHO_ETH_CNF,
	ECHO_SERIAL_REQ,
	ECHO_SERIAL_CNF,
	NAD_SERIALNO_READ_REQ,
	NAD_SERIALNO_READ_CNF,
	SW_VER_READ_REQ,
	SW_VER_READ_CNF,
	SIM_READ_REQ,
	SIM_READ_CNF,
	IMEI_READ_REQ,
	IMEI_READ_CNF,
	EMMC_SIZE_READ_REQ,
	EMMC_SIZE_READ_CNF,
	RADIO_CHECK_REQ,
	RADIO_CHECK_CNF,
	DATA_CONNECTION_CHECK_REQ,
	DATA_CONNECTION_CHECK_CNF,
	AUDIO_LOOP_TEST_REQ,
	AUDIO_LOOP_TEST_CNF,
	A2B_TEST_REQ,
	A2B_TEST_CNF,
	SLEEP_REQ,
	SLEEP_CNF
};


#endif  /* #ifndef _COMMON_H_*/
